[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Matt W. <liljerk@gmail.com>" ]
publish = false

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
